# Generated by Django 4.2.11 on 2025-12-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['season', 'number']},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('series', 'season', 'number')},
        ),
    ]
