# Generated by Django 4.2.11 on 2025-12-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(help_text='URL da imagem/capa exibida no banner')),
                ('trailer_url', models.URLField(blank=True, help_text='(Opcional) link do trailer')),
                ('href', models.CharField(blank=True, help_text='(Opcional) link ao clicar. Ex: /movies/1/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor primeiro)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
