# Generated by Django 4.2.11 on 2025-12-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_homebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
